# Generated by Django 3.1.4 on 2021-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getInfoGrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_grup', models.TextField()),
                ('chat_id', models.CharField(max_length=60)),
                ('prefix', models.TextField()),
                ('nsfw', models.IntegerField()),
                ('AntiToxic', models.IntegerField()),
                ('LastUpdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pengguna', models.CharField(max_length=30)),
                ('dibuat', models.DateTimeField()),
                ('konten', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('umur', models.IntegerField()),
                ('gender', models.TextField()),
                ('bio', models.TextField()),
                ('profile', models.TextField()),
                ('chat_id', models.TextField()),
                ('bot_save', models.TextField()),
                ('LastUpdate', models.DateTimeField()),
            ],
        ),
    ]
